apiVersion: helm.cilium.io/v2
kind: CiliumConfig
metadata:
  name: cilium-config
  namespace: kube-system
spec:
  operator:
    replicas: 1
    extraArgs:
      - --disable-node-port=true
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  hostPort:
    enabled: false  # Disable hostPort to prevent port conflicts
  kubeProxyReplacement: "strict"
  cni:
    install: true
    chainingMode: "none"
    exclusive: true
  daemon:
    runAsUser: 0
    runAsGroup: 0
    enabled: true
  ipam:
    mode: "kubernetes"
  containerRuntime:
    integration: "containerd"
  tunnel: "disabled"
  autoDirectNodeRoutes: true
  enableIPv4Masquerade: true
  bpf:
    masquerade: true
  installNoConntrackIptablesRules: true
